version: "2"
services:
  db:
    container_name: local-mongo
    hostname: local-mongo
    image: mongo:3.2
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"
      - "db-config:/data/configdb"
volumes:
  db-data:
    driver: local
  db-config:
    driver: local
